development:
  adapter: sqlite3
  database: db/btenca_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/btenca_test.sqlite3
  pool: 5
  timeout: 5000
 
production:
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5
  timeout: 5000
  database: btenca_production
